# Generated by Django 5.2.7 on 2025-10-20 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cliente_email_remove_cliente_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_usuario',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('RESTAURANTE', 'Dono de Restaurante')], default='CLIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='dono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurantes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
